analytics: {}
color:
  brandColors:
    - '#708837'
    - '#391408'
    - '#9a352d'
    - '#f1db32'
    - '#95adca'
  brandStrength: 0.8125
  lightness: 0.5625
  rhythmicContrast: 1
  saturation: 0.25
cta: {}
layout_spectrum: 0.7726
name: SEOrigami
opengraph: {}
purpose: []
typography_spectrum: 0.300164
